spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #不配置的方式也能转发，有用过Zuul的同学肯定都知道，Zuul默认会为所有服务都进行转发操作，只需要在访问路径上指定要访问的服务即可，通过这种方式就不用为每个服务都去配置转发规则，当新加了服务的时候，不用去配置路由规则和重启网关。
          lower-case-service-id: true #这个大写的名称还是有很大的影响，如果我们从Zull升级到Spring Cloud Gateway的话意味着请求地址有改变，或者重新配置每个服务的路由地址，通过源码我发现可以做到兼容处理，再增加一个配置即可：