spring:
  application:
    name: hystrix-turbine
server:
  port: 40002
# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）

# 显示所有健康状态
management:
  #  endpoint:
  #    health:
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# http://localhost:20001/hystrix需要带上参数，参数是spring.application.name集群服务名称 访问http://localhost:40001/turbine.stream?cluster=FEIGN-1
#turbine:
#  aggregator:
#    cluster-config: RIBBON-1,FEIGN-1
#  app-config: ribbon-1,feign-1

# 监控相应的服务 http://localhost:20001/hystrix直接访问，不需要带上集群名称http://localhost:40001/turbine.stream
turbine:
  aggregator:
    cluster-config: default
  app-config: ribbon-1,feign-1
  cluster-name-expression: "'default'" #Spring El表达式 new String("default");