spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 192.168.1.32
    port: 5672
    username: guest
    password: guest
  # 开启发送确认
    publisher-confirms: true
  # 开启发送失败退回
    publisher-returns:  true
  # 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual