spring:
  profiles:
    active: dev
  application:
    name: eureka
#单机
server:
  port: 8761
eureka:
  datacenter: cloud           # 修改Eureka监控页面的System Status Data center
  environment: test            # 修改Eureka监控页面的System Status Environment
# 显示所有健康状态
management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: "*"
