server:
  port: 10001
spring:
  application:
    name: server-1 #建议小写
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.1.70:9411/ # 指定了 Zipkin 服务器的地址
# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #      defaultZone: http://user:password123@localhost:8761/eureka/ #2.1.0无法注册到Eureka中
  #    healthcheck:
  #      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    prefer-ip-address: true #IP地址
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]} # 随机端口号
#    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）