server:
  port: 50001
spring:
  application:
    name: gateway-zuul
  profiles:
    active: regex
# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #      defaultZone: http://user:password123@localhost:8761/eureka/ #2.1.0无法注册到Eureka中
  #    healthcheck:
  #      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    prefer-ip-address: true #IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）

# http://192.168.1.224:40001/zuul/{微服务ServiceId}/{路径url} /zuul替代路径绕过Spring DispatcherServlet
# Zuul上传图片超时设置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


# 显示所有健康状态
management:
  endpoint:
    health:
      show-details: always
  #      通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的
  endpoints:
    web:
      exposure:
        include: "*"