#在访问微服务的ServiceId前面加上前缀
#  当stripPrefix=true的时候 （http://127.0.0.1:8181/api/user/list -> http://192.168.1.100:8080/user/list）
#  当stripPrefix=false的时候（http://127.0.0.1:8181/api/user/list -> http://192.168.1.100:8080/api/user/list）
zuul:
  #  全局配置：prefix和strip-prefix是联合使用
  prefix: /api #加上前缀
  strip-prefix: false #
  # 局部配置：只针对server-1微服务路由-针对某一个路由
  server-1:
    path: /s-1/**
    stripPrefix: false

logging:
  level:
    com.netflix: debug