# 这个应用主机名可以用eureka.instance.appname代替
spring:
  application:
    name: ribbon-1
server:
  port: 20001
#  servlet:
#    context-path: /ribbon-1
# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #    appname: ribbon-1 #可以用来代替spring.application.name
    prefer-ip-address: true #IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）

# 显示所有健康状态
management:
  endpoint:
    health:
      show-details: always
  # Spring2.0特性全部在actuaton下面 management.endpoints.web.exposure.include这个是用来暴露 endpoints 的
  #  springcloud 中使用 hystrix-dashboard 进行监控的时候启动报错”path”:”/actuator/hystrix.stream”,”status”:404,”error”:”Not Found”
  endpoints:
    web:
      exposure:
        #        include: ["hystrix-stream"] #但是actuator/health就无法访问了，所以还可以选择全部放开。
        include: "*"